// Generated by CoffeeScript 1.3.3
(function() {

  self.onmessage = function(event) {
    var data, intensity, pixel, type, _i, _len, _ref, _ref1, _step;
    _ref = [event.data.type, event.data.data], type = _ref[0], data = _ref[1];
    switch (type) {
      case 'perform':
        intensity = 0;
        _ref1 = data.pixels;
        for (_i = 0, _len = _ref1.length, _step = 4; _i < _len; _i += _step) {
          pixel = _ref1[_i];
          if (pixel != null) {
            intensity += pixel;
          }
        }
        return self.postMessage({
          type: 'complete',
          data: {
            intensity: intensity,
            timestamp: data.timestamp
          }
        });
    }
  };

}).call(this);
