// Generated by CoffeeScript 1.3.3
(function() {

  self.onmessage = function(event) {
    var c, data, sum, type, _ref;
    _ref = [event.data.type, event.data.data], type = _ref[0], data = _ref[1];
    switch (type) {
      case 'perform':
        sum = data.numbers.reduce(function(t, s) {
          return t + s;
        });
        c = function() {
          return self.postMessage({
            type: 'complete',
            data: {
              sum: sum
            }
          });
        };
        return setTimeout(c, Math.random() * 5000 + 500);
    }
  };

}).call(this);
