// Generated by CoffeeScript 1.3.3
(function() {

  self.onmessage = function(event) {
    var c, data, string, type, _ref;
    _ref = [event.data.type, event.data.data], type = _ref[0], data = _ref[1];
    switch (type) {
      case 'perform':
        string = data.string.toUpperCase();
        c = function() {
          return self.postMessage({
            type: 'complete',
            data: {
              string: string
            }
          });
        };
        return setTimeout(c, Math.random() * 3000 + 500);
    }
  };

}).call(this);
