// Generated by CoffeeScript 1.3.3
(function() {

  window.Orange = require('orange');

  window.URL = window.URL || window.webkitURL;

  window.requestAnimationFrame = window.webkitRequestAnimationFrame;

  navigator.getUserMedia = navigator.getUserMedia || navigator.webkitGetUserMedia;

  window.HeartrateJS = {
    Models: {},
    Collections: {},
    Views: {},
    Utils: {},
    Settings: {
      waitingDuration: 5000,
      measurementDuration: 10000
    },
    initialize: function() {
      new HeartrateJS.Router();
      return Backbone.history.start();
    }
  };

  $(function() {
    return HeartrateJS.initialize();
  });

}).call(this);
