// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  HeartrateJS.Views.Calculating = (function(_super) {

    __extends(Calculating, _super);

    function Calculating() {
      return Calculating.__super__.constructor.apply(this, arguments);
    }

    Calculating.prototype.el = '#container';

    Calculating.prototype.initialize = function() {
      return this.template = _.template($('#tmpl-calculating').text());
    };

    Calculating.prototype.render = function() {
      this.$el.html(this.template());
      return this;
    };

    return Calculating;

  })(Backbone.View);

}).call(this);
