// Generated by CoffeeScript 1.3.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  HeartrateJS.Views.Instructions = (function(_super) {

    __extends(Instructions, _super);

    function Instructions() {
      this.render = __bind(this.render, this);
      return Instructions.__super__.constructor.apply(this, arguments);
    }

    Instructions.prototype.el = '#container';

    Instructions.prototype.initialize = function() {
      return this.template = _.template($('#tmpl-instructions').text());
    };

    Instructions.prototype.render = function() {
      this.$el.html(this.template());
      return this;
    };

    return Instructions;

  })(Backbone.View);

}).call(this);
