// Generated by CoffeeScript 1.3.3
(function() {
  var _ref;

  if ((_ref = window.Orange) == null) {
    window.Orange = {};
  }

  Orange.settings = {
    maxThreadPoolSize: 4,
    workersPath: '/lib/workers/'
  };

  Orange.Queue = new Orange._Queue;

  Orange.ThreadManager = new Orange._ThreadManager;

}).call(this);
