// Generated by CoffeeScript 1.3.3
(function() {

  String.prototype.underscore = function() {
    return this.replace(/([A-Z])/g, function($1) {
      return "_" + $1.toLowerCase();
    });
  };

}).call(this);
