// Generated by CoffeeScript 1.3.3
(function() {
  var _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  if ((_ref = window.Orange) == null) {
    window.Orange = {};
  }

  Orange.Eventable = (function() {

    function Eventable() {
      this.trigger = __bind(this.trigger, this);

      this.off = __bind(this.off, this);

      this.on = __bind(this.on, this);
      this._subscriptions = {};
    }

    Eventable.prototype.on = function(event, callback) {
      if (this._subscriptions[event] == null) {
        this._subscriptions[event] = [];
      }
      return this._subscriptions[event].push(callback);
    };

    Eventable.prototype.off = function(event, callback) {
      var cb, e, subscriptions, _ref1;
      if (this._subscriptions[event] != null) {
        if (callback != null) {
          return this._subscriptions[event] = (function() {
            var _i, _len, _ref1, _results;
            _ref1 = this._subscriptions[event];
            _results = [];
            for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
              cb = _ref1[_i];
              if (cb !== callback) {
                _results.push(cb);
              }
            }
            return _results;
          }).call(this);
        } else {
          subscriptions = [];
          _ref1 = this._subscriptions;
          for (e in _ref1) {
            cb = _ref1[e];
            if (e !== event) {
              subscriptions[e] = cb;
            }
          }
          return this._subscriptions = subscriptions;
        }
      }
    };

    Eventable.prototype.trigger = function(event, data) {
      var _i, _len, _ref1, _results;
      if (this._subscriptions[event] != null) {
        _ref1 = this._subscriptions[event];
        _results = [];
        for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
          event = _ref1[_i];
          _results.push(event.call(this, data));
        }
        return _results;
      }
    };

    return Eventable;

  })();

}).call(this);
