// Generated by CoffeeScript 1.3.3
(function() {
  var _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  if ((_ref = window.Orange) == null) {
    window.Orange = {};
  }

  Orange.JobSet = (function(_super) {

    __extends(JobSet, _super);

    function JobSet() {
      this._jobComplete = __bind(this._jobComplete, this);
      JobSet.__super__.constructor.call(this);
      this._jobs = [];
      this._completeCount = 0;
    }

    JobSet.prototype.push = function(job) {
      job.on('complete', this._jobComplete);
      return this._jobs.push(job);
    };

    JobSet.prototype._jobComplete = function() {
      if (++this._completeCount >= this._jobs.length) {
        return this.trigger('complete', this._jobs);
      }
    };

    return JobSet;

  })(Orange.Eventable);

}).call(this);
