// Generated by CoffeeScript 1.3.3
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  if ((_ref = window.Orange) == null) {
    window.Orange = {};
  }

  Orange._Queue = (function(_super) {

    __extends(_Queue, _super);

    function _Queue() {
      _Queue.__super__.constructor.call(this);
      this.jobs = [];
      this.length = 0;
    }

    _Queue.prototype.push = function(job) {
      var _this = this;
      this.jobs.push(job);
      this.length = this.jobs.length;
      job.on('complete', function() {
        return _this.trigger('job:completed');
      });
      this.trigger('job:pushed');
      return this.jobs;
    };

    _Queue.prototype.pop = function() {
      var job;
      job = this.jobs.shift();
      this.length = this.jobs.length;
      return job;
    };

    return _Queue;

  })(Orange.Eventable);

}).call(this);
