// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  HeartrateJS.Models.DataPoint = (function(_super) {

    __extends(DataPoint, _super);

    function DataPoint() {
      return DataPoint.__super__.constructor.apply(this, arguments);
    }

    DataPoint.prototype.enqueue = function() {
      var job,
        _this = this;
      job = new Orange.Job('calculate_intensity', {
        pixels: this.get('pixels'),
        timestamp: this.get('timestamp')
      });
      job.on('complete', function(data) {
        return _this.set('intensity', data.intensity);
      });
      return job;
    };

    return DataPoint;

  })(Backbone.Model);

}).call(this);
